/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    "createRule": null,
    "deleteRule": null,
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text"
      },
      {
        "cascadeDelete": true,
        "collectionId": "_pb_users_auth_",
        "hidden": false,
        "id": "relation3479234172",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "owner",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation"
      },
      {
        "hidden": false,
        "id": "file3309110367",
        "maxSelect": 1,
        "maxSize": 0,
        "mimeTypes": [],
        "name": "image",
        "presentable": false,
        "protected": false,
        "required": false,
        "system": false,
        "thumbs": [],
        "type": "file"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1164680044",
        "max": 0,
        "min": 0,
        "name": "pet_name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": true,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text2181884964",
        "max": 0,
        "min": 0,
        "name": "reg_name",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3968011019",
        "max": 0,
        "min": 0,
        "name": "UELN_number",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "number3470689431",
        "max": null,
        "min": null,
        "name": "chip_number",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3638780425",
        "max": 0,
        "min": 0,
        "name": "chip_placement",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text256487343",
        "max": 0,
        "min": 0,
        "name": "tattoo_number",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "select4172253263",
        "maxSelect": 1,
        "name": "breed",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "select",
        "values": [
          "american_curly",
          "andalusian",
          "arabian",
          "ardennes",
          "clydesdale",
          "connemara",
          "dartmoor",
          "exmoor",
          "fjord_horse",
          "frieser",
          "thoroughbred",
          "gotland_russ",
          "haflinger",
          "hanoverians",
          "holsteiner",
          "irish_cob",
          "icelandic_horse",
          "cold_blooded_trotter",
          "swedish_caspian_horse",
          "KWPN",
          "lipizzan",
          "lusitanian",
          "miniature_horse",
          "morgan",
          "mustang",
          "new_forest",
          "north_swedish_horse",
          "oldenburger",
          "paint",
          "PRE",
          "quarter",
          "bashkir_horse",
          "shetland_pony",
          "shire",
          "swedish_riding_pony",
          "tinker",
          "trakehner",
          "warmblood",
          "warmblood_trotter",
          "welsh",
          "other"
        ]
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text1716930793",
        "max": 0,
        "min": 0,
        "name": "color",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text296607184",
        "max": 0,
        "min": 0,
        "name": "patterns",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "date2464439331",
        "max": "",
        "min": "",
        "name": "birthdate",
        "presentable": false,
        "required": false,
        "system": false,
        "type": "date"
      },
      {
        "hidden": false,
        "id": "number4115522831",
        "max": null,
        "min": null,
        "name": "height",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text3475321272",
        "max": 0,
        "min": 0,
        "name": "father",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text450002714",
        "max": 0,
        "min": 0,
        "name": "mother",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text"
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate"
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate"
      }
    ],
    "id": "pbc_1058254908",
    "indexes": [],
    "listRule": null,
    "name": "horses",
    "system": false,
    "type": "base",
    "updateRule": null,
    "viewRule": null
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_1058254908");

  return app.delete(collection);
})
